FROM python:3.8-slim 
RUN pip install fastapi celery redis uvicorn numpy pillow gunicorn flask[async] gevent aiohttp 
RUN pip install inference[gpu]
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
COPY tasks.py .
COPY serve.py .
COPY patched.py .
ENTRYPOINT uvicorn serve:app --port 8000 --host 0.0.0.0