FROM python:3.8-slim 
RUN pip install celery numpy pillow redis inference[gpu]
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
COPY tasks.py .
COPY infer.py .
ENTRYPOINT python infer.py